//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPUserControls.UPSOnline {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConsigneeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Address2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Zip5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Zip4Field;
        
        private int ClassificationField;
        
        private int StatusField;
        
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Consignee {
            get {
                return this.ConsigneeField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsigneeField, value) != true)) {
                    this.ConsigneeField = value;
                    this.RaisePropertyChanged("Consignee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address1 {
            get {
                return this.Address1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address1Field, value) != true)) {
                    this.Address1Field = value;
                    this.RaisePropertyChanged("Address1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Address2 {
            get {
                return this.Address2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Address2Field, value) != true)) {
                    this.Address2Field = value;
                    this.RaisePropertyChanged("Address2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Zip5 {
            get {
                return this.Zip5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Zip5Field, value) != true)) {
                    this.Zip5Field = value;
                    this.RaisePropertyChanged("Zip5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Zip4 {
            get {
                return this.Zip4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Zip4Field, value) != true)) {
                    this.Zip4Field = value;
                    this.RaisePropertyChanged("Zip4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int Classification {
            get {
                return this.ClassificationField;
            }
            set {
                if ((this.ClassificationField.Equals(value) != true)) {
                    this.ClassificationField = value;
                    this.RaisePropertyChanged("Classification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UPSOnline.UPSOnlineSoap")]
    public interface UPSOnlineSoap {
        
        // CODEGEN: Generating message contract since element name addr1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateClassifyAddressXML", ReplyAction="*")]
        CPUserControls.UPSOnline.ValidateClassifyAddressXMLResponse ValidateClassifyAddressXML(CPUserControls.UPSOnline.ValidateClassifyAddressXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateClassifyAddressXML", ReplyAction="*")]
        System.Threading.Tasks.Task<CPUserControls.UPSOnline.ValidateClassifyAddressXMLResponse> ValidateClassifyAddressXMLAsync(CPUserControls.UPSOnline.ValidateClassifyAddressXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateClassifyAddress", ReplyAction="*")]
        CPUserControls.UPSOnline.ValidateClassifyAddressResponse ValidateClassifyAddress(CPUserControls.UPSOnline.ValidateClassifyAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateClassifyAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<CPUserControls.UPSOnline.ValidateClassifyAddressResponse> ValidateClassifyAddressAsync(CPUserControls.UPSOnline.ValidateClassifyAddressRequest request);
        
        // CODEGEN: Generating message contract since element name addr1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassifyAddressXML", ReplyAction="*")]
        CPUserControls.UPSOnline.ClassifyAddressXMLResponse ClassifyAddressXML(CPUserControls.UPSOnline.ClassifyAddressXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassifyAddressXML", ReplyAction="*")]
        System.Threading.Tasks.Task<CPUserControls.UPSOnline.ClassifyAddressXMLResponse> ClassifyAddressXMLAsync(CPUserControls.UPSOnline.ClassifyAddressXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassifyAddress", ReplyAction="*")]
        CPUserControls.UPSOnline.ClassifyAddressResponse ClassifyAddress(CPUserControls.UPSOnline.ClassifyAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClassifyAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<CPUserControls.UPSOnline.ClassifyAddressResponse> ClassifyAddressAsync(CPUserControls.UPSOnline.ClassifyAddressRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateClassifyAddressXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateClassifyAddressXML", Namespace="http://tempuri.org/", Order=0)]
        public CPUserControls.UPSOnline.ValidateClassifyAddressXMLRequestBody Body;
        
        public ValidateClassifyAddressXMLRequest() {
        }
        
        public ValidateClassifyAddressXMLRequest(CPUserControls.UPSOnline.ValidateClassifyAddressXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateClassifyAddressXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addr1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string addr2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string zip5;
        
        public ValidateClassifyAddressXMLRequestBody() {
        }
        
        public ValidateClassifyAddressXMLRequestBody(string addr1, string addr2, string city, string state, string zip5) {
            this.addr1 = addr1;
            this.addr2 = addr2;
            this.city = city;
            this.state = state;
            this.zip5 = zip5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateClassifyAddressXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateClassifyAddressXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public CPUserControls.UPSOnline.ValidateClassifyAddressXMLResponseBody Body;
        
        public ValidateClassifyAddressXMLResponse() {
        }
        
        public ValidateClassifyAddressXMLResponse(CPUserControls.UPSOnline.ValidateClassifyAddressXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateClassifyAddressXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CPUserControls.UPSOnline.Response ValidateClassifyAddressXMLResult;
        
        public ValidateClassifyAddressXMLResponseBody() {
        }
        
        public ValidateClassifyAddressXMLResponseBody(CPUserControls.UPSOnline.Response ValidateClassifyAddressXMLResult) {
            this.ValidateClassifyAddressXMLResult = ValidateClassifyAddressXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateClassifyAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateClassifyAddress", Namespace="http://tempuri.org/", Order=0)]
        public CPUserControls.UPSOnline.ValidateClassifyAddressRequestBody Body;
        
        public ValidateClassifyAddressRequest() {
        }
        
        public ValidateClassifyAddressRequest(CPUserControls.UPSOnline.ValidateClassifyAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateClassifyAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addr1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string addr2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string zip5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string zip4;
        
        public ValidateClassifyAddressRequestBody() {
        }
        
        public ValidateClassifyAddressRequestBody(string addr1, string addr2, string city, string state, string zip5, string zip4) {
            this.addr1 = addr1;
            this.addr2 = addr2;
            this.city = city;
            this.state = state;
            this.zip5 = zip5;
            this.zip4 = zip4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateClassifyAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateClassifyAddressResponse", Namespace="http://tempuri.org/", Order=0)]
        public CPUserControls.UPSOnline.ValidateClassifyAddressResponseBody Body;
        
        public ValidateClassifyAddressResponse() {
        }
        
        public ValidateClassifyAddressResponse(CPUserControls.UPSOnline.ValidateClassifyAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateClassifyAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ValidateClassifyAddressResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string addr1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string addr2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string zip5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string zip4;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int status;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int classification;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int count;
        
        public ValidateClassifyAddressResponseBody() {
        }
        
        public ValidateClassifyAddressResponseBody(int ValidateClassifyAddressResult, string addr1, string addr2, string city, string state, string zip5, string zip4, int status, int classification, int count) {
            this.ValidateClassifyAddressResult = ValidateClassifyAddressResult;
            this.addr1 = addr1;
            this.addr2 = addr2;
            this.city = city;
            this.state = state;
            this.zip5 = zip5;
            this.zip4 = zip4;
            this.status = status;
            this.classification = classification;
            this.count = count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClassifyAddressXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClassifyAddressXML", Namespace="http://tempuri.org/", Order=0)]
        public CPUserControls.UPSOnline.ClassifyAddressXMLRequestBody Body;
        
        public ClassifyAddressXMLRequest() {
        }
        
        public ClassifyAddressXMLRequest(CPUserControls.UPSOnline.ClassifyAddressXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClassifyAddressXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addr1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string addr2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string zip5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string zip4;
        
        public ClassifyAddressXMLRequestBody() {
        }
        
        public ClassifyAddressXMLRequestBody(string addr1, string addr2, string city, string state, string zip5, string zip4) {
            this.addr1 = addr1;
            this.addr2 = addr2;
            this.city = city;
            this.state = state;
            this.zip5 = zip5;
            this.zip4 = zip4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClassifyAddressXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClassifyAddressXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public CPUserControls.UPSOnline.ClassifyAddressXMLResponseBody Body;
        
        public ClassifyAddressXMLResponse() {
        }
        
        public ClassifyAddressXMLResponse(CPUserControls.UPSOnline.ClassifyAddressXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClassifyAddressXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CPUserControls.UPSOnline.Response ClassifyAddressXMLResult;
        
        public ClassifyAddressXMLResponseBody() {
        }
        
        public ClassifyAddressXMLResponseBody(CPUserControls.UPSOnline.Response ClassifyAddressXMLResult) {
            this.ClassifyAddressXMLResult = ClassifyAddressXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClassifyAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClassifyAddress", Namespace="http://tempuri.org/", Order=0)]
        public CPUserControls.UPSOnline.ClassifyAddressRequestBody Body;
        
        public ClassifyAddressRequest() {
        }
        
        public ClassifyAddressRequest(CPUserControls.UPSOnline.ClassifyAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClassifyAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addr1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string addr2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string zip5;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string zip4;
        
        public ClassifyAddressRequestBody() {
        }
        
        public ClassifyAddressRequestBody(string addr1, string addr2, string city, string state, string zip5, string zip4) {
            this.addr1 = addr1;
            this.addr2 = addr2;
            this.city = city;
            this.state = state;
            this.zip5 = zip5;
            this.zip4 = zip4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClassifyAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClassifyAddressResponse", Namespace="http://tempuri.org/", Order=0)]
        public CPUserControls.UPSOnline.ClassifyAddressResponseBody Body;
        
        public ClassifyAddressResponse() {
        }
        
        public ClassifyAddressResponse(CPUserControls.UPSOnline.ClassifyAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClassifyAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ClassifyAddressResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int classification;
        
        public ClassifyAddressResponseBody() {
        }
        
        public ClassifyAddressResponseBody(int ClassifyAddressResult, int classification) {
            this.ClassifyAddressResult = ClassifyAddressResult;
            this.classification = classification;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UPSOnlineSoapChannel : CPUserControls.UPSOnline.UPSOnlineSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UPSOnlineSoapClient : System.ServiceModel.ClientBase<CPUserControls.UPSOnline.UPSOnlineSoap>, CPUserControls.UPSOnline.UPSOnlineSoap {
        
        public UPSOnlineSoapClient() {
        }
        
        public UPSOnlineSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UPSOnlineSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPSOnlineSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPSOnlineSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CPUserControls.UPSOnline.ValidateClassifyAddressXMLResponse CPUserControls.UPSOnline.UPSOnlineSoap.ValidateClassifyAddressXML(CPUserControls.UPSOnline.ValidateClassifyAddressXMLRequest request) {
            return base.Channel.ValidateClassifyAddressXML(request);
        }
        
        public CPUserControls.UPSOnline.Response ValidateClassifyAddressXML(string addr1, string addr2, string city, string state, string zip5) {
            CPUserControls.UPSOnline.ValidateClassifyAddressXMLRequest inValue = new CPUserControls.UPSOnline.ValidateClassifyAddressXMLRequest();
            inValue.Body = new CPUserControls.UPSOnline.ValidateClassifyAddressXMLRequestBody();
            inValue.Body.addr1 = addr1;
            inValue.Body.addr2 = addr2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip5 = zip5;
            CPUserControls.UPSOnline.ValidateClassifyAddressXMLResponse retVal = ((CPUserControls.UPSOnline.UPSOnlineSoap)(this)).ValidateClassifyAddressXML(inValue);
            return retVal.Body.ValidateClassifyAddressXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPUserControls.UPSOnline.ValidateClassifyAddressXMLResponse> CPUserControls.UPSOnline.UPSOnlineSoap.ValidateClassifyAddressXMLAsync(CPUserControls.UPSOnline.ValidateClassifyAddressXMLRequest request) {
            return base.Channel.ValidateClassifyAddressXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPUserControls.UPSOnline.ValidateClassifyAddressXMLResponse> ValidateClassifyAddressXMLAsync(string addr1, string addr2, string city, string state, string zip5) {
            CPUserControls.UPSOnline.ValidateClassifyAddressXMLRequest inValue = new CPUserControls.UPSOnline.ValidateClassifyAddressXMLRequest();
            inValue.Body = new CPUserControls.UPSOnline.ValidateClassifyAddressXMLRequestBody();
            inValue.Body.addr1 = addr1;
            inValue.Body.addr2 = addr2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip5 = zip5;
            return ((CPUserControls.UPSOnline.UPSOnlineSoap)(this)).ValidateClassifyAddressXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CPUserControls.UPSOnline.ValidateClassifyAddressResponse CPUserControls.UPSOnline.UPSOnlineSoap.ValidateClassifyAddress(CPUserControls.UPSOnline.ValidateClassifyAddressRequest request) {
            return base.Channel.ValidateClassifyAddress(request);
        }
        
        public int ValidateClassifyAddress(ref string addr1, ref string addr2, ref string city, ref string state, ref string zip5, ref string zip4, out int status, out int classification, out int count) {
            CPUserControls.UPSOnline.ValidateClassifyAddressRequest inValue = new CPUserControls.UPSOnline.ValidateClassifyAddressRequest();
            inValue.Body = new CPUserControls.UPSOnline.ValidateClassifyAddressRequestBody();
            inValue.Body.addr1 = addr1;
            inValue.Body.addr2 = addr2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip5 = zip5;
            inValue.Body.zip4 = zip4;
            CPUserControls.UPSOnline.ValidateClassifyAddressResponse retVal = ((CPUserControls.UPSOnline.UPSOnlineSoap)(this)).ValidateClassifyAddress(inValue);
            addr1 = retVal.Body.addr1;
            addr2 = retVal.Body.addr2;
            city = retVal.Body.city;
            state = retVal.Body.state;
            zip5 = retVal.Body.zip5;
            zip4 = retVal.Body.zip4;
            status = retVal.Body.status;
            classification = retVal.Body.classification;
            count = retVal.Body.count;
            return retVal.Body.ValidateClassifyAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPUserControls.UPSOnline.ValidateClassifyAddressResponse> CPUserControls.UPSOnline.UPSOnlineSoap.ValidateClassifyAddressAsync(CPUserControls.UPSOnline.ValidateClassifyAddressRequest request) {
            return base.Channel.ValidateClassifyAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPUserControls.UPSOnline.ValidateClassifyAddressResponse> ValidateClassifyAddressAsync(string addr1, string addr2, string city, string state, string zip5, string zip4) {
            CPUserControls.UPSOnline.ValidateClassifyAddressRequest inValue = new CPUserControls.UPSOnline.ValidateClassifyAddressRequest();
            inValue.Body = new CPUserControls.UPSOnline.ValidateClassifyAddressRequestBody();
            inValue.Body.addr1 = addr1;
            inValue.Body.addr2 = addr2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip5 = zip5;
            inValue.Body.zip4 = zip4;
            return ((CPUserControls.UPSOnline.UPSOnlineSoap)(this)).ValidateClassifyAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CPUserControls.UPSOnline.ClassifyAddressXMLResponse CPUserControls.UPSOnline.UPSOnlineSoap.ClassifyAddressXML(CPUserControls.UPSOnline.ClassifyAddressXMLRequest request) {
            return base.Channel.ClassifyAddressXML(request);
        }
        
        public CPUserControls.UPSOnline.Response ClassifyAddressXML(string addr1, string addr2, string city, string state, string zip5, string zip4) {
            CPUserControls.UPSOnline.ClassifyAddressXMLRequest inValue = new CPUserControls.UPSOnline.ClassifyAddressXMLRequest();
            inValue.Body = new CPUserControls.UPSOnline.ClassifyAddressXMLRequestBody();
            inValue.Body.addr1 = addr1;
            inValue.Body.addr2 = addr2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip5 = zip5;
            inValue.Body.zip4 = zip4;
            CPUserControls.UPSOnline.ClassifyAddressXMLResponse retVal = ((CPUserControls.UPSOnline.UPSOnlineSoap)(this)).ClassifyAddressXML(inValue);
            return retVal.Body.ClassifyAddressXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPUserControls.UPSOnline.ClassifyAddressXMLResponse> CPUserControls.UPSOnline.UPSOnlineSoap.ClassifyAddressXMLAsync(CPUserControls.UPSOnline.ClassifyAddressXMLRequest request) {
            return base.Channel.ClassifyAddressXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPUserControls.UPSOnline.ClassifyAddressXMLResponse> ClassifyAddressXMLAsync(string addr1, string addr2, string city, string state, string zip5, string zip4) {
            CPUserControls.UPSOnline.ClassifyAddressXMLRequest inValue = new CPUserControls.UPSOnline.ClassifyAddressXMLRequest();
            inValue.Body = new CPUserControls.UPSOnline.ClassifyAddressXMLRequestBody();
            inValue.Body.addr1 = addr1;
            inValue.Body.addr2 = addr2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip5 = zip5;
            inValue.Body.zip4 = zip4;
            return ((CPUserControls.UPSOnline.UPSOnlineSoap)(this)).ClassifyAddressXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CPUserControls.UPSOnline.ClassifyAddressResponse CPUserControls.UPSOnline.UPSOnlineSoap.ClassifyAddress(CPUserControls.UPSOnline.ClassifyAddressRequest request) {
            return base.Channel.ClassifyAddress(request);
        }
        
        public int ClassifyAddress(string addr1, string addr2, string city, string state, string zip5, string zip4, out int classification) {
            CPUserControls.UPSOnline.ClassifyAddressRequest inValue = new CPUserControls.UPSOnline.ClassifyAddressRequest();
            inValue.Body = new CPUserControls.UPSOnline.ClassifyAddressRequestBody();
            inValue.Body.addr1 = addr1;
            inValue.Body.addr2 = addr2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip5 = zip5;
            inValue.Body.zip4 = zip4;
            CPUserControls.UPSOnline.ClassifyAddressResponse retVal = ((CPUserControls.UPSOnline.UPSOnlineSoap)(this)).ClassifyAddress(inValue);
            classification = retVal.Body.classification;
            return retVal.Body.ClassifyAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPUserControls.UPSOnline.ClassifyAddressResponse> CPUserControls.UPSOnline.UPSOnlineSoap.ClassifyAddressAsync(CPUserControls.UPSOnline.ClassifyAddressRequest request) {
            return base.Channel.ClassifyAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPUserControls.UPSOnline.ClassifyAddressResponse> ClassifyAddressAsync(string addr1, string addr2, string city, string state, string zip5, string zip4) {
            CPUserControls.UPSOnline.ClassifyAddressRequest inValue = new CPUserControls.UPSOnline.ClassifyAddressRequest();
            inValue.Body = new CPUserControls.UPSOnline.ClassifyAddressRequestBody();
            inValue.Body.addr1 = addr1;
            inValue.Body.addr2 = addr2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zip5 = zip5;
            inValue.Body.zip4 = zip4;
            return ((CPUserControls.UPSOnline.UPSOnlineSoap)(this)).ClassifyAddressAsync(inValue);
        }
    }
}
