//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPUserControls.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Interstate")]
        public string ISTATETaxId {
            get {
                return ((string)(this["ISTATETaxId"]));
            }
            set {
                this["ISTATETaxId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("168")]
        public int ISTATETaxKey {
            get {
                return ((int)(this["ISTATETaxKey"]));
            }
            set {
                this["ISTATETaxKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0")]
        public decimal ISTATETaxRate {
            get {
                return ((decimal)(this["ISTATETaxRate"]));
            }
            set {
                this["ISTATETaxRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Government")]
        public string GOVTaxId {
            get {
                return ((string)(this["GOVTaxId"]));
            }
            set {
                this["GOVTaxId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172")]
        public int GOVTaxKey {
            get {
                return ((int)(this["GOVTaxKey"]));
            }
            set {
                this["GOVTaxKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0")]
        public decimal GovTaxRate {
            get {
                return ((decimal)(this["GovTaxRate"]));
            }
            set {
                this["GovTaxRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("International")]
        public string INTLTaxId {
            get {
                return ((string)(this["INTLTaxId"]));
            }
            set {
                this["INTLTaxId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("178")]
        public int INTLTaxKey {
            get {
                return ((int)(this["INTLTaxKey"]));
            }
            set {
                this["INTLTaxKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0")]
        public decimal INTLTaxRate {
            get {
                return ((decimal)(this["INTLTaxRate"]));
            }
            set {
                this["INTLTaxRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Los Angeles")]
        public string MPKTaxId {
            get {
                return ((string)(this["MPKTaxId"]));
            }
            set {
                this["MPKTaxId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public int MPKTaxKey {
            get {
                return ((int)(this["MPKTaxKey"]));
            }
            set {
                this["MPKTaxKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0950")]
        public decimal MPKTaxRate {
            get {
                return ((decimal)(this["MPKTaxRate"]));
            }
            set {
                this["MPKTaxRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1715 +WA Base")]
        public string SEATaxId {
            get {
                return ((string)(this["SEATaxId"]));
            }
            set {
                this["SEATaxId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("293")]
        public int SEATaxKey {
            get {
                return ((int)(this["SEATaxKey"]));
            }
            set {
                this["SEATaxKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.100")]
        public decimal SEATaxRate {
            get {
                return ((decimal)(this["SEATaxRate"]));
            }
            set {
                this["SEATaxRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missouri")]
        public string STLTaxId {
            get {
                return ((string)(this["STLTaxId"]));
            }
            set {
                this["STLTaxId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("170")]
        public int STLTaxKey {
            get {
                return ((int)(this["STLTaxKey"]));
            }
            set {
                this["STLTaxKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.08863")]
        public decimal STLTaxRate {
            get {
                return ((decimal)(this["STLTaxRate"]));
            }
            set {
                this["STLTaxRate"] = value;
            }
        }
    }
}
