//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPUserControls.CASalesTax {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CATaxResponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CATaxResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfidenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JurisdictionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TACField;
        
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Rate {
            get {
                return this.RateField;
            }
            set {
                if ((object.ReferenceEquals(this.RateField, value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Confidence {
            get {
                return this.ConfidenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfidenceField, value) != true)) {
                    this.ConfidenceField = value;
                    this.RaisePropertyChanged("Confidence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Jurisdiction {
            get {
                return this.JurisdictionField;
            }
            set {
                if ((object.ReferenceEquals(this.JurisdictionField, value) != true)) {
                    this.JurisdictionField = value;
                    this.RaisePropertyChanged("Jurisdiction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TAC {
            get {
                return this.TACField;
            }
            set {
                if ((object.ReferenceEquals(this.TACField, value) != true)) {
                    this.TACField = value;
                    this.RaisePropertyChanged("TAC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CASalesTax.CATaxRateAPISoap")]
    public interface CATaxRateAPISoap {
        
        // CODEGEN: Generating message contract since element name address from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTaxRateXML", ReplyAction="*")]
        CPUserControls.CASalesTax.GetTaxRateXMLResponse GetTaxRateXML(CPUserControls.CASalesTax.GetTaxRateXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTaxRateXML", ReplyAction="*")]
        System.Threading.Tasks.Task<CPUserControls.CASalesTax.GetTaxRateXMLResponse> GetTaxRateXMLAsync(CPUserControls.CASalesTax.GetTaxRateXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTaxRate", ReplyAction="*")]
        CPUserControls.CASalesTax.GetTaxRateResponse GetTaxRate(CPUserControls.CASalesTax.GetTaxRateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTaxRate", ReplyAction="*")]
        System.Threading.Tasks.Task<CPUserControls.CASalesTax.GetTaxRateResponse> GetTaxRateAsync(CPUserControls.CASalesTax.GetTaxRateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTaxRateXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTaxRateXML", Namespace="http://tempuri.org/", Order=0)]
        public CPUserControls.CASalesTax.GetTaxRateXMLRequestBody Body;
        
        public GetTaxRateXMLRequest() {
        }
        
        public GetTaxRateXMLRequest(CPUserControls.CASalesTax.GetTaxRateXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTaxRateXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string zip;
        
        public GetTaxRateXMLRequestBody() {
        }
        
        public GetTaxRateXMLRequestBody(string address, string city, string zip) {
            this.address = address;
            this.city = city;
            this.zip = zip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTaxRateXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTaxRateXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public CPUserControls.CASalesTax.GetTaxRateXMLResponseBody Body;
        
        public GetTaxRateXMLResponse() {
        }
        
        public GetTaxRateXMLResponse(CPUserControls.CASalesTax.GetTaxRateXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTaxRateXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CPUserControls.CASalesTax.CATaxResponse GetTaxRateXMLResult;
        
        public GetTaxRateXMLResponseBody() {
        }
        
        public GetTaxRateXMLResponseBody(CPUserControls.CASalesTax.CATaxResponse GetTaxRateXMLResult) {
            this.GetTaxRateXMLResult = GetTaxRateXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTaxRateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTaxRate", Namespace="http://tempuri.org/", Order=0)]
        public CPUserControls.CASalesTax.GetTaxRateRequestBody Body;
        
        public GetTaxRateRequest() {
        }
        
        public GetTaxRateRequest(CPUserControls.CASalesTax.GetTaxRateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTaxRateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string zip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string taxrate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string county;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string jurisdiction;
        
        public GetTaxRateRequestBody() {
        }
        
        public GetTaxRateRequestBody(string address, string city, string zip, string taxrate, string county, string jurisdiction) {
            this.address = address;
            this.city = city;
            this.zip = zip;
            this.taxrate = taxrate;
            this.county = county;
            this.jurisdiction = jurisdiction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTaxRateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTaxRateResponse", Namespace="http://tempuri.org/", Order=0)]
        public CPUserControls.CASalesTax.GetTaxRateResponseBody Body;
        
        public GetTaxRateResponse() {
        }
        
        public GetTaxRateResponse(CPUserControls.CASalesTax.GetTaxRateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTaxRateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetTaxRateResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string taxrate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string county;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string jurisdiction;
        
        public GetTaxRateResponseBody() {
        }
        
        public GetTaxRateResponseBody(int GetTaxRateResult, string taxrate, string county, string jurisdiction) {
            this.GetTaxRateResult = GetTaxRateResult;
            this.taxrate = taxrate;
            this.county = county;
            this.jurisdiction = jurisdiction;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CATaxRateAPISoapChannel : CPUserControls.CASalesTax.CATaxRateAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CATaxRateAPISoapClient : System.ServiceModel.ClientBase<CPUserControls.CASalesTax.CATaxRateAPISoap>, CPUserControls.CASalesTax.CATaxRateAPISoap {
        
        public CATaxRateAPISoapClient() {
        }
        
        public CATaxRateAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CATaxRateAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CATaxRateAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CATaxRateAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CPUserControls.CASalesTax.GetTaxRateXMLResponse CPUserControls.CASalesTax.CATaxRateAPISoap.GetTaxRateXML(CPUserControls.CASalesTax.GetTaxRateXMLRequest request) {
            return base.Channel.GetTaxRateXML(request);
        }
        
        public CPUserControls.CASalesTax.CATaxResponse GetTaxRateXML(string address, string city, string zip) {
            CPUserControls.CASalesTax.GetTaxRateXMLRequest inValue = new CPUserControls.CASalesTax.GetTaxRateXMLRequest();
            inValue.Body = new CPUserControls.CASalesTax.GetTaxRateXMLRequestBody();
            inValue.Body.address = address;
            inValue.Body.city = city;
            inValue.Body.zip = zip;
            CPUserControls.CASalesTax.GetTaxRateXMLResponse retVal = ((CPUserControls.CASalesTax.CATaxRateAPISoap)(this)).GetTaxRateXML(inValue);
            return retVal.Body.GetTaxRateXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPUserControls.CASalesTax.GetTaxRateXMLResponse> CPUserControls.CASalesTax.CATaxRateAPISoap.GetTaxRateXMLAsync(CPUserControls.CASalesTax.GetTaxRateXMLRequest request) {
            return base.Channel.GetTaxRateXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPUserControls.CASalesTax.GetTaxRateXMLResponse> GetTaxRateXMLAsync(string address, string city, string zip) {
            CPUserControls.CASalesTax.GetTaxRateXMLRequest inValue = new CPUserControls.CASalesTax.GetTaxRateXMLRequest();
            inValue.Body = new CPUserControls.CASalesTax.GetTaxRateXMLRequestBody();
            inValue.Body.address = address;
            inValue.Body.city = city;
            inValue.Body.zip = zip;
            return ((CPUserControls.CASalesTax.CATaxRateAPISoap)(this)).GetTaxRateXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CPUserControls.CASalesTax.GetTaxRateResponse CPUserControls.CASalesTax.CATaxRateAPISoap.GetTaxRate(CPUserControls.CASalesTax.GetTaxRateRequest request) {
            return base.Channel.GetTaxRate(request);
        }
        
        public int GetTaxRate(string address, string city, string zip, ref string taxrate, ref string county, ref string jurisdiction) {
            CPUserControls.CASalesTax.GetTaxRateRequest inValue = new CPUserControls.CASalesTax.GetTaxRateRequest();
            inValue.Body = new CPUserControls.CASalesTax.GetTaxRateRequestBody();
            inValue.Body.address = address;
            inValue.Body.city = city;
            inValue.Body.zip = zip;
            inValue.Body.taxrate = taxrate;
            inValue.Body.county = county;
            inValue.Body.jurisdiction = jurisdiction;
            CPUserControls.CASalesTax.GetTaxRateResponse retVal = ((CPUserControls.CASalesTax.CATaxRateAPISoap)(this)).GetTaxRate(inValue);
            taxrate = retVal.Body.taxrate;
            county = retVal.Body.county;
            jurisdiction = retVal.Body.jurisdiction;
            return retVal.Body.GetTaxRateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CPUserControls.CASalesTax.GetTaxRateResponse> CPUserControls.CASalesTax.CATaxRateAPISoap.GetTaxRateAsync(CPUserControls.CASalesTax.GetTaxRateRequest request) {
            return base.Channel.GetTaxRateAsync(request);
        }
        
        public System.Threading.Tasks.Task<CPUserControls.CASalesTax.GetTaxRateResponse> GetTaxRateAsync(string address, string city, string zip, string taxrate, string county, string jurisdiction) {
            CPUserControls.CASalesTax.GetTaxRateRequest inValue = new CPUserControls.CASalesTax.GetTaxRateRequest();
            inValue.Body = new CPUserControls.CASalesTax.GetTaxRateRequestBody();
            inValue.Body.address = address;
            inValue.Body.city = city;
            inValue.Body.zip = zip;
            inValue.Body.taxrate = taxrate;
            inValue.Body.county = county;
            inValue.Body.jurisdiction = jurisdiction;
            return ((CPUserControls.CASalesTax.CATaxRateAPISoap)(this)).GetTaxRateAsync(inValue);
        }
    }
}
